"""empty message

Revision ID: b177e43516b1
Revises: c5ed7c32d3f0
Create Date: 2020-04-04 16:16:26.808830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b177e43516b1'
down_revision = 'c5ed7c32d3f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=50), nullable=True))
    op.drop_index('username', table_name='user')
    op.create_unique_constraint(None, 'user', ['firstname'])
    op.create_unique_constraint(None, 'user', ['lastname'])
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('username', 'user', ['username'], unique=True)
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
